allow-help-menu: true

messages:
  prefix: '&8[&5NoStrip&8]'
  unknown-command: '&cUnknown Command'
  must-be-player: '&cYou Must Be A Player To Use This Command!'
  no-permission: '&cPermission Required! Contact server admin!'
  no-axe-permission: '&cAxe Is Denied! Permission(s) Required!'
  toggle-message: '&2Log Stripping Toggled {status}'
  config-reloaded: '&2Config Reloaded!'